# .github/workflows/ci.yml

name: CI

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and start services
        run: docker compose up -d --build

      - name: Wait for services 
        run: sleep 20

      - name: Install Node Dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Run PyTest tests
        run: docker compose exec -T flask pytest

      - name: Stop and shutdown
        run: docker compose down
