# .github/workflows/ci.yml

name: CI

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
      TRAFFIC_API_KEY: ${{ secrets.TRAFFIC_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Build and start services
        run: docker compose up -d --build

      - name: Wait for services 
        run: sleep 20

      - name: Install Node Dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Setup Python to run PyTests
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
        
      - name: install python deps
        run: pip install -r tools/requirements.txt
      
      - name: Run PyTest tests
        run: pytest

      - name: Stop and shutdown
        run: docker compose down
